item {
  id: 1
  name: 'Green'
}

item {
  id: 2
  name: 'Red'
}

item {
  id: 3
  name: 'Yellow'
}

item {
  id: 4
  name: 'off'
}

item {
  id: 5
  name: 'Rear'
}

item {
  id: 6
  name: 'Unknown'
}
